const express = require ('express');
const mongoose = require("mongoose");
const PORT = process.env.PORT || 3000;
const bodyParser = require('body-parser');

//routes
const rApiFetch = require(__dirname + "/routes/get-api-fetch");
const rGetPathAdmin = require(__dirname + "/routes/get-path-admin");
const rGetId = require(__dirname + "/routes/get-id");
const rPostAddingNewProduct = require(__dirname + "/routes/post-addingnewproduct");



//init app
const app = express();

//adding ejs for dynamic rendering
app.set('view engine', 'ejs');


let url = "mongodb://localhost:27017/peterdb";

// define a middleware that can be used by the server to read JSON payload.
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

mongoose.connect(url, { useUnifiedTopology: true, useNewUrlParser: true }, (err,res)=>{
  if(err){console.log (err + "Database error")}
});

const connection = mongoose.connection;

connection.once("open", function() {
    console.log("MongoDB database connection established successfully");

    app.listen(PORT,()=> console.log("server is running on " + PORT));
  });


//general routes for integrating passport in the future
app.get("/", (req, res) => {
    res.render("index");
  });

  app.get("/login", (req, res) => {
    res.render("login");
  });

  app.post("/login", (req, res) => {
 
  });

  app.get("/register", (req, res) => {
    res.render("register");
  });

  app.post("/register", (req, res) => {
    req.body.name
    req.body.password
  });


//fetching everything to see if it was posted if unsure
 
app.get("/api/fetch", rApiFetch);


//admin path to add new product
app.get("/path/admin", rGetPathAdmin);

//user path to render product info from db based on the unique id generated by mongo
app.get("/:id",rGetId);

//once added by admin - form will post product info via this path - new product route

app.post("/addingnewproduct",rPostAddingNewProduct);


